---
- hosts: all
  sudo: true
  vars:
    packages:
      - "wget"
      - "tcpdump"
      - "nc"
  handlers:
    - name: Do Something
      debug: msg="true"
  tasks:
    - name: Install our packages
      yum:
        name: "{{item}}"
        state: "present"
      with_items: packages 

    - name: Remove nc
      yum:
        name: "nc"
        state: "absent"

    - group:
        name: "superusers"
        state: "present"

    - user:
        name: "{{item}}"
        state: "present"
        groups: "superusers"
      with_items:
        - "michaelc"
        - "michelled"
        - "obamab"
        - "barryb"
        - "user01"
      notify: "Do Something"

    - command: rpm -qa wget 

- hosts: all
  sudo: true
  tasks:
    - name: Install our packages
      service:
        name: "postfix"
        state: "stopped"
        enabled: false

    - name: Remove user 
      user:
        name: "michaelc"
        state: "absent"
